spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      url: ${REDIS_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 900000      # 15m
    refresh-token-expiration: 604800000  # 7d
